version: "3"
services:

  metabase-app:
    image: metabase/metabase
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /home/ciceromoura/Área de Trabalho/docker:/metabase-data

networks: 
  metabase-compose-network:
    driver: bridge
